apiVersion: apps/v1
kind: Deployment
metadata:
  name: studyai-frontend
  namespace: studyai
  labels:
    app: studyai-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: studyai-frontend
  template:
    metadata:
      labels:
        app: studyai-frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/yourusername/studyai/frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_API_URL
          value: "https://api.studyai.yourdomain.com"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: studyai-frontend-service
  namespace: studyai
spec:
  selector:
    app: studyai-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP